default_stages: [pre-commit, manual]

repos:
  # Ruff (reemplaza a flake8 y isort)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
        exclude: (^venv/)|(^notebooks/.*\.ipynb$)
      - id: ruff-format
        exclude: (^venv/)|(^notebooks/.*\.ipynb$)

  # Static code analyzer
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.2
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - --rcfile=.code_quality/.pylintrc
        exclude: (^venv/)|(^notebooks/.*\.ipynb$)

  # Common security issues analysis
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args:
          - -c
          - .code_quality/bandit.yaml
        exclude: (^venv/)|(^notebooks/.*\.ipynb$)

  # Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          - --config-file=.code_quality/mypy.ini
        additional_dependencies:
          - types-PyMySQL
          - types-requests
        exclude: (^venv/)|(^notebooks/.*\.ipynb$)

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []