"""add_puntaje_columns

Revision ID: 2e69113e1d24
Revises: 2bc2972cc56a
Create Date: 2025-06-03 18:58:06.064595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e69113e1d24'
down_revision: Union[str, None] = '2bc2972cc56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM inference_model")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference_model', sa.Column('puntaje_1', sa.Float(), nullable=False))
    op.add_column('inference_model', sa.Column('puntaje_2', sa.Float(), nullable=False))
    op.add_column('inference_model', sa.Column('puntaje_3', sa.Float(), nullable=False))
    op.add_column('inference_model', sa.Column('puntaje_4', sa.Float(), nullable=False))
    op.add_column('inference_model', sa.Column('puntaje_5', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inference_model', 'puntaje_5')
    op.drop_column('inference_model', 'puntaje_4')
    op.drop_column('inference_model', 'puntaje_3')
    op.drop_column('inference_model', 'puntaje_2')
    op.drop_column('inference_model', 'puntaje_1')
    # ### end Alembic commands ###
