"""add anomalia table

Revision ID: d108571b159c
Revises:
Create Date: 2025-05-06 16:11:44.691910

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d108571b159c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomalia_data",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("AREA", sa.String(length=255), nullable=True),
        sa.Column("item_288", sa.Integer(), nullable=False),
        sa.Column("odt", sa.Integer(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("PLAN_COMERCIAL", sa.String(length=255), nullable=False),
        sa.Column("Descripcion", sa.Text(), nullable=True),
        sa.Column("reincidente", sa.String(length=50), nullable=False),
        sa.Column("Anomalia_conf", sa.String(length=255), nullable=False),
        sa.Column("ZONA", sa.String(length=100), nullable=False),
        sa.Column("año", sa.Integer(), nullable=False),
        sa.Column("LATI_USU", sa.Float(), nullable=False),
        sa.Column("LONG_USU", sa.Float(), nullable=False),
        sa.Column("NIVEL", sa.Float(), nullable=False),
        sa.Column("item_68", sa.Boolean(), nullable=False),
        sa.Column("item_74", sa.Boolean(), nullable=False),
        sa.Column("item_237", sa.Boolean(), nullable=False),
        sa.Column("item_248", sa.String(length=255), nullable=False),
        sa.Column("item_597", sa.String(length=255), nullable=False),
        sa.Column("item_602", sa.String(length=255), nullable=False),
        sa.Column("item_108", sa.String(length=255), nullable=False),
        sa.Column("item_43", sa.String(length=255), nullable=False),
        sa.Column("item_603", sa.String(length=255), nullable=False),
        sa.Column("item_599", sa.String(length=255), nullable=False),
        sa.Column("item_35", sa.String(length=255), nullable=False),
        sa.Column("item_598", sa.String(length=255), nullable=False),
        sa.Column("item_33", sa.String(length=255), nullable=False),
        sa.Column("item_601", sa.String(length=255), nullable=False),
        sa.Column("item_24", sa.String(length=255), nullable=False),
        sa.Column("item_23", sa.String(length=255), nullable=False),
        sa.Column("fecha_creacion", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anomalia_data")
    # ### end Alembic commands ###
