"""add inference_model table

Revision ID: 2bc2972cc56a
Revises: d108571b159c
Create Date: 2025-05-20 11:54:46.008476

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bc2972cc56a"
down_revision: Union[str, None] = "d108571b159c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inference_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("Orden", sa.Integer(), nullable=False),
        sa.Column("Usuario", sa.Integer(), nullable=False),
        sa.Column("Ejecucion", sa.String(length=255), nullable=False),
        sa.Column("Codigo", sa.String(length=255), nullable=True),
        sa.Column("Descripcion", sa.Text(), nullable=False),
        sa.Column("Motivo", sa.Text(), nullable=True),
        sa.Column("kWh_Rec", sa.Float(), nullable=True),
        sa.Column("Factor", sa.Float(), nullable=True),
        sa.Column("data_id", sa.Float(), nullable=True),
        sa.Column("Nombre", sa.String(length=255), nullable=True),
        sa.Column("Factor_1", sa.Float(), nullable=True),
        sa.Column("AREA", sa.String(length=255), nullable=True),
        sa.Column("PLAN_COMERCIAL", sa.String(length=255), nullable=True),
        sa.Column("TRAFO_OPEN", sa.String(length=255), nullable=True),
        sa.Column("FASES", sa.Float(), nullable=True),
        sa.Column("KVA", sa.Float(), nullable=True),
        sa.Column("LATI_USU", sa.Float(), nullable=True),
        sa.Column("LONG_USU", sa.Float(), nullable=True),
        sa.Column("puntaje", sa.Float(), nullable=True),
        sa.Column("evaluacion", sa.Float(), nullable=True),
        sa.Column("Zona", sa.String(length=255), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("cluster_0", sa.Float(), nullable=False),
        sa.Column("cluster_1", sa.Float(), nullable=False),
        sa.Column("cluster_2", sa.Float(), nullable=False),
        sa.Column("fecha_carga", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inference_model")
    # ### end Alembic commands ###
